export const initialData = [
    {
        id: "#5412448",
        modelName: "Blonde Drizzle",
        modelType: "Extraction",
        description: "Edit customer and there truncate max-w-xs truncate max-w-xs truncate max-w-xs",
        createdOn: "29/02/2024",
        lastTrainedOn: "02/03/2024",
        status: "Active",
    },
    {
        id: "#5412449",
        modelName: "Golden Spark",
        modelType: "Classification",
        description: "Analyze product data for better segmentation max-w-xs",
        createdOn: "01/03/2024",
        lastTrainedOn: "05/03/2024",
        status: "Inactive",
    },
    {
        id: "#5412450",
        modelName: "Crimson Flow",
        modelType: "Prediction",
        description: "Predict customer behavior max-w-xs max-w-xs",
        createdOn: "10/03/2024",
        lastTrainedOn: "15/03/2024",
        status: "Active",
    },
    {
        id: "#5412451",
        modelName: "Emerald Wave",
        modelType: "Clustering",
        description: "Group users based on preferences max-w-xs truncate",
        createdOn: "12/03/2024",
        lastTrainedOn: "20/03/2024",
        status: "Active",
    },
    {
        id: "#5412452",
        modelName: "Sapphire Edge",
        modelType: "Anomaly Detection",
        description: "Detect irregularities in system logs max-w-xs",
        createdOn: "15/03/2024",
        lastTrainedOn: "25/03/2024",
        status: "Active",
    },
    {
        id: "#5412453",
        modelName: "Amber Glow",
        modelType: "Regression",
        description: "Forecast sales trends max-w-xs truncate",
        createdOn: "18/03/2024",
        lastTrainedOn: "28/03/2024",
        status: "Inactive",
    },
    {
        id: "#5412454",
        modelName: "Cobalt Storm",
        modelType: "Extraction",
        description: "Extract entities from text max-w-xs truncate max-w-xs",
        createdOn: "20/03/2024",
        lastTrainedOn: "30/03/2024",
        status: "Active",
    },
    {
        id: "#5412455",
        modelName: "Ivory Whisper",
        modelType: "Classification",
        description: "Classify documents into categories max-w-xs",
        createdOn: "22/03/2024",
        lastTrainedOn: "01/04/2024",
        status: "Active",
    },
    {
        id: "#5412456",
        modelName: "Obsidian Shadow",
        modelType: "Prediction",
        description: "Predict market shifts max-w-xs truncate",
        createdOn: "25/03/2024",
        lastTrainedOn: "05/04/2024",
        status: "Inactive",
    },
    {
        id: "#5412457",
        modelName: "Ruby Flame",
        modelType: "Clustering",
        description: "Group similar patterns in datasets max-w-xs",
        createdOn: "28/03/2024",
        lastTrainedOn: "08/04/2024",
        status: "Active",
    },
    {
        id: "#5412458",
        modelName: "Silver Horizon",
        modelType: "Anomaly Detection",
        description: "Identify outliers in financial data max-w-xs",
        createdOn: "30/03/2024",
        lastTrainedOn: "10/04/2024",
        status: "Active",
    },
    {
        id: "#5412459",
        modelName: "Onyx Pulse",
        modelType: "Regression",
        description: "Estimate customer lifetime value max-w-xs truncate",
        createdOn: "01/04/2024",
        lastTrainedOn: "12/04/2024",
        status: "Inactive",
    },
    {
        id: "#5412460",
        modelName: "Crimson Frost",
        modelType: "Extraction",
        description: "Extract relevant data from forms max-w-xs",
        createdOn: "05/04/2024",
        lastTrainedOn: "15/04/2024",
        status: "Active",
    },
    {
        id: "#5412461",
        modelName: "Golden Beam",
        modelType: "Classification",
        description: "Categorize support tickets max-w-xs",
        createdOn: "07/04/2024",
        lastTrainedOn: "17/04/2024",
        status: "Active",
    },
    {
        id: "#5412462",
        modelName: "Azure Tide",
        modelType: "Prediction",
        description: "Predict demand for seasonal products max-w-xs",
        createdOn: "09/04/2024",
        lastTrainedOn: "20/04/2024",
        status: "Inactive",
    },
    {
        id: "#5412463",
        modelName: "Topaz Glow",
        modelType: "Clustering",
        description: "Organize users into groups max-w-xs",
        createdOn: "12/04/2024",
        lastTrainedOn: "22/04/2024",
        status: "Active",
    },
    {
        id: "#5412464",
        modelName: "Pearl Vision",
        modelType: "Anomaly Detection",
        description: "Spot anomalies in time series data max-w-xs",
        createdOn: "15/04/2024",
        lastTrainedOn: "25/04/2024",
        status: "Active",
    },
    {
        id: "#5412465",
        modelName: "Platinum Blaze",
        modelType: "Regression",
        description: "Predict energy consumption max-w-xs",
        createdOn: "18/04/2024",
        lastTrainedOn: "28/04/2024",
        status: "Inactive",
    },
    {
        id: "#5412466",
        modelName: "Jade Mist",
        modelType: "Extraction",
        description: "Extract insights from surveys max-w-xs",
        createdOn: "20/04/2024",
        lastTrainedOn: "30/04/2024",
        status: "Active",
    },
    {
        id: "#5412467",
        modelName: "Opal Wave",
        modelType: "Classification",
        description: "Sort image datasets max-w-xs",
        createdOn: "23/04/2024",
        lastTrainedOn: "03/05/2024",
        status: "Active",
    },
    {
        id: "#5412468",
        modelName: "Velvet Ray",
        modelType: "Prediction",
        description: "Forecast weather patterns max-w-xs",
        createdOn: "25/04/2024",
        lastTrainedOn: "05/05/2024",
        status: "Active",
    },
    {
        id: "#5412469",
        modelName: "Bronze Crest",
        modelType: "Classification",
        description: "Classify product defects max-w-xs",
        createdOn: "27/04/2024",
        lastTrainedOn: "07/05/2024",
        status: "Inactive",
    },
    {
        id: "#5412470",
        modelName: "Lilac Dream",
        modelType: "Clustering",
        description: "Segment customer demographics max-w-xs",
        createdOn: "01/05/2024",
        lastTrainedOn: "10/05/2024",
        status: "Active",
    },
    {
        id: "#5412471",
        modelName: "Ivory Bloom",
        modelType: "Regression",
        description: "Predict housing prices max-w-xs",
        createdOn: "03/05/2024",
        lastTrainedOn: "13/05/2024",
        status: "Inactive",
    },
    {
        id: "#5412472",
        modelName: "Coral Sky",
        modelType: "Extraction",
        description: "Extract metadata from images max-w-xs",
        createdOn: "05/05/2024",
        lastTrainedOn: "15/05/2024",
        status: "Active",
    },
    {
        id: "#5412473",
        modelName: "Amber Streak",
        modelType: "Anomaly Detection",
        description: "Find unusual transactions max-w-xs",
        createdOn: "07/05/2024",
        lastTrainedOn: "17/05/2024",
        status: "Inactive",
    },
    {
        id: "#5412474",
        modelName: "Cyan Drift",
        modelType: "Classification",
        description: "Organize video content max-w-xs",
        createdOn: "09/05/2024",
        lastTrainedOn: "19/05/2024",
        status: "Active",
    },
    {
        id: "#5412475",
        modelName: "Ebony Spark",
        modelType: "Prediction",
        description: "Forecast traffic flow max-w-xs",
        createdOn: "11/05/2024",
        lastTrainedOn: "21/05/2024",
        status: "Inactive",
    },
    {
        id: "#5412476",
        modelName: "Azure Peak",
        modelType: "Clustering",
        description: "Organize similar purchase data max-w-xs",
        createdOn: "13/05/2024",
        lastTrainedOn: "23/05/2024",
        status: "Active",
    },
    {
        id: "#5412477",
        modelName: "Scarlet Veil",
        modelType: "Extraction",
        description: "Extract keywords from documents max-w-xs",
        createdOn: "15/05/2024",
        lastTrainedOn: "25/05/2024",
        status: "Inactive",
    },
    {
        id: "#5412478",
        modelName: "Quartz Beam",
        modelType: "Classification",
        description: "Label social media posts max-w-xs",
        createdOn: "17/05/2024",
        lastTrainedOn: "27/05/2024",
        status: "Active",
    },
    {
        id: "#5412479",
        modelName: "Ruby Crest",
        modelType: "Prediction",
        description: "Estimate delivery times max-w-xs",
        createdOn: "19/05/2024",
        lastTrainedOn: "29/05/2024",
        status: "Inactive",
    },
    {
        id: "#5412480",
        modelName: "Topaz Edge",
        modelType: "Clustering",
        description: "Identify similar patterns in sales data max-w-xs",
        createdOn: "21/05/2024",
        lastTrainedOn: "31/05/2024",
        status: "Active",
    },
    {
        id: "#5412481",
        modelName: "Violet Glow",
        modelType: "Extraction",
        description: "Extract fields from scanned receipts max-w-xs",
        createdOn: "23/05/2024",
        lastTrainedOn: "02/06/2024",
        status: "Inactive",
    },
    {
        id: "#5412482",
        modelName: "Sienna Blaze",
        modelType: "Regression",
        description: "Predict advertising ROI max-w-xs",
        createdOn: "25/05/2024",
        lastTrainedOn: "04/06/2024",
        status: "Active",
    },
    {
        id: "#5412483",
        modelName: "Emerald Frost",
        modelType: "Anomaly Detection",
        description: "Spot outliers in production data max-w-xs",
        createdOn: "27/05/2024",
        lastTrainedOn: "06/06/2024",
        status: "Inactive",
    },
    {
        id: "#5412484",
        modelName: "Golden Stream",
        modelType: "Prediction",
        description: "Forecast inventory needs max-w-xs",
        createdOn: "29/05/2024",
        lastTrainedOn: "08/06/2024",
        status: "Active",
    },
    {
        id: "#5412485",
        modelName: "Cobalt Drift",
        modelType: "Classification",
        description: "Categorize technical support cases max-w-xs",
        createdOn: "31/05/2024",
        lastTrainedOn: "10/06/2024",
        status: "Inactive",
    },
    {
        id: "#5412486",
        modelName: "Amethyst Flame",
        modelType: "Regression",
        description: "Estimate project completion time max-w-xs",
        createdOn: "02/06/2024",
        lastTrainedOn: "12/06/2024",
        status: "Active",
    },
    {
        id: "#5412487",
        modelName: "Celestial Stream",
        modelType: "Anomaly Detection",
        description: "Find unexpected behaviors in IoT devices max-w-xs",
        createdOn: "04/06/2024",
        lastTrainedOn: "14/06/2024",
        status: "Inactive",
    },
];
