export const initialData = [
    {
        id: "#5412448",
        modelName: "Blonde Drizzle",
        modelType: "Extraction",
        description: "Edit customer and there truncate max-w-xs truncate max-w-xs truncate max-w-xs",
        createdOn: "29/02/2024",
        lastTrainedOn: "02/03/2024",
        status: "Active",
    },
    {
        id: "#5412449",
        modelName: "Golden Spark",
        modelType: "Classification",
        description: "Analyze product data for better segmentation max-w-xs",
        createdOn: "01/03/2024",
        lastTrainedOn: "05/03/2024",
        status: "Inactive",
    },
    {
        id: "#5412450",
        modelName: "Crimson Flow",
        modelType: "Prediction",
        description: "Predict customer behavior max-w-xs max-w-xs",
        createdOn: "10/03/2024",
        lastTrainedOn: "15/03/2024",
        status: "Active",
    },
    {
        id: "#5412451",
        modelName: "Emerald Wave",
        modelType: "Clustering",
        description: "Group users based on preferences max-w-xs truncate",
        createdOn: "12/03/2024",
        lastTrainedOn: "20/03/2024",
        status: "Active",
    },
    {
        id: "#5412452",
        modelName: "Sapphire Edge",
        modelType: "Anomaly Detection",
        description: "Detect irregularities in system logs max-w-xs",
        createdOn: "15/03/2024",
        lastTrainedOn: "25/03/2024",
        status: "Active",
    },
    {
        id: "#5412453",
        modelName: "Amber Glow",
        modelType: "Regression",
        description: "Forecast sales trends max-w-xs truncate",
        createdOn: "18/03/2024",
        lastTrainedOn: "28/03/2024",
        status: "Inactive",
    },
    {
        id: "#5412454",
        modelName: "Cobalt Storm",
        modelType: "Extraction",
        description: "Extract entities from text max-w-xs truncate max-w-xs",
        createdOn: "20/03/2024",
        lastTrainedOn: "30/03/2024",
        status: "Active",
    },
    {
        id: "#5412455",
        modelName: "Ivory Whisper",
        modelType: "Classification",
        description: "Classify documents into categories max-w-xs",
        createdOn: "22/03/2024",
        lastTrainedOn: "01/04/2024",
        status: "Active",
    },
    {
        id: "#5412456",
        modelName: "Obsidian Shadow",
        modelType: "Prediction",
        description: "Predict market shifts max-w-xs truncate",
        createdOn: "25/03/2024",
        lastTrainedOn: "05/04/2024",
        status: "Inactive",
    },
    {
        id: "#5412457",
        modelName: "Ruby Flame",
        modelType: "Clustering",
        description: "Group similar patterns in datasets max-w-xs",
        createdOn: "28/03/2024",
        lastTrainedOn: "08/04/2024",
        status: "Active",
    },
    {
        id: "#5412458",
        modelName: "Silver Horizon",
        modelType: "Anomaly Detection",
        description: "Identify outliers in financial data max-w-xs",
        createdOn: "30/03/2024",
        lastTrainedOn: "10/04/2024",
        status: "Active",
    },
    {
        id: "#5412459",
        modelName: "Onyx Pulse",
        modelType: "Regression",
        description: "Estimate customer lifetime value max-w-xs truncate",
        createdOn: "01/04/2024",
        lastTrainedOn: "12/04/2024",
        status: "Inactive",
    },
    {
        id: "#5412460",
        modelName: "Crimson Frost",
        modelType: "Extraction",
        description: "Extract relevant data from forms max-w-xs",
        createdOn: "05/04/2024",
        lastTrainedOn: "15/04/2024",
        status: "Active",
    },
    {
        id: "#5412461",
        modelName: "Golden Beam",
        modelType: "Classification",
        description: "Categorize support tickets max-w-xs",
        createdOn: "07/04/2024",
        lastTrainedOn: "17/04/2024",
        status: "Active",
    },
    {
        id: "#5412462",
        modelName: "Azure Tide",
        modelType: "Prediction",
        description: "Predict demand for seasonal products max-w-xs",
        createdOn: "09/04/2024",
        lastTrainedOn: "20/04/2024",
        status: "Inactive",
    },
    {
        id: "#5412463",
        modelName: "Topaz Glow",
        modelType: "Clustering",
        description: "Organize users into groups max-w-xs",
        createdOn: "12/04/2024",
        lastTrainedOn: "22/04/2024",
        status: "Active",
    },
    {
        id: "#5412464",
        modelName: "Pearl Vision",
        modelType: "Anomaly Detection",
        description: "Spot anomalies in time series data max-w-xs",
        createdOn: "15/04/2024",
        lastTrainedOn: "25/04/2024",
        status: "Active",
    },
    {
        id: "#5412465",
        modelName: "Platinum Blaze",
        modelType: "Regression",
        description: "Predict energy consumption max-w-xs",
        createdOn: "18/04/2024",
        lastTrainedOn: "28/04/2024",
        status: "Inactive",
    },
    {
        id: "#5412466",
        modelName: "Jade Mist",
        modelType: "Extraction",
        description: "Extract insights from surveys max-w-xs",
        createdOn: "20/04/2024",
        lastTrainedOn: "30/04/2024",
        status: "Active",
    },
    {
        id: "#5412467",
        modelName: "Opal Wave",
        modelType: "Classification",
        description: "Sort image datasets max-w-xs",
        createdOn: "23/04/2024",
        lastTrainedOn: "03/05/2024",
        status: "Active",
    },
];
